DROP TABLE IF EXISTS `#__products`;
DROP TABLE IF EXISTS `#__products_activities`;
DROP TABLE IF EXISTS `#__products_address_states`;
DROP TABLE IF EXISTS `#__products_clients`;
DROP TABLE IF EXISTS `#__products_fields`;
DROP TABLE IF EXISTS `#__products_fields_values`;
DROP TABLE IF EXISTS `#__products_orders`;
DROP TABLE IF EXISTS `#__products_orders_items`;
DROP TABLE IF EXISTS `#__products_payments`;
